name: Request a song.
description: Request a song to the creator.
labels: [Song Request]
body:
  - type: input
    id: songname
    attributes:
      label: "Link to the song."
      description: "Find a song that you like, and input the link in this box."
      placeholder: "https://youtu.be/..."
    validations:
      required: true
      
  - type: input
    id: songbpm
    attributes:
      label: "If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers."
      description: "If the Base BPM isn't found, use this > https://www.beatsperminuteonline.com/"
      placeholder: "180"
    validations:
      required: false
