name: 'Request a song.'
description: Request a song to be added in Nael\'s Ultimate spamming Mod
labels: [Song Request]
body:
  - type: input
    id: songname
    attributes:
      label: "Link to the song."
      description: "Find a song that you like, and input the link in this box."
      placeholder: "https://youtu.be/..."
    validations:
      required: true
      
  - type: input
    id: songbpm
    attributes:
      label: "BPM"
      description: "There should be a BPM in the video! If the Base BPM isn't found, use this > https://www.beatsperminuteonline.com/"
      placeholder: "180"
    validations:
      required: true

  - type: input
    id: extras
    attributes:
      label: "Extra Sprites"
      description: "(You will be credited, unless you know who made the sprites.)"
      placeholder: "https://drive.google.com/file/d/..."
    validations:
      required: false
