name: Song Removal Request.
description: Want to remove the song in my mod for reasons? Click this one!
labels: [Song Removal Request]
body:
  - type: input
    id: songname
    attributes:
      label: "Link/Name of the song"
      placeholder: "https://youtu.be/... | Cease (REMAKE)"
    validations:
      required: true
      
  - type: textarea
    id: why
    attributes:
      label: "Explain why you want this song removed."
      placeholder: "Hi, [owner of the song] here, and i want you to remove my song in my mod please, thank you."
    validations:
      required: false
      
  - type: dropdown
    id: own
    attributes:
      label: "Do you own this song?"
      description: "If you set to Choose an option then it will be denied"
      options:
        - "Choose an option."
        - "Yes (must show proof)"
        - "No"
    validations:
      required: true
