name: Song Removal Request.
description: Want to remove a song in my mod? Click this!
labels: [Song Removal Request]
body:
  - type: textarea
    id: songname
    attributes:
      label: "Link/Name of the song"
    validations:
      required: true
      
  - type: textarea
    id: why
    attributes:
      label: "Explain why you want this song removed. Also make sure you own the song first!!"
    validations:
      required: false
      
  - type: dropdown
    id: oclt
    attributes:
      label: "Do you own this song?"
      options:
        - "Yes (must show proof)"
        - "No"
    validations:
      required: true
